name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
categories:
  - title: '🚀 Features'
    when:
      labels:
        - 'feature'
        - 'enhancement'
  - title: '⚠️ Breaking Changes'
    when:
      labels:
        - 'breaking'
  - title: '🐛 Bug Fixes'
    when:
      labels:
        - 'fix'
        - 'bugfix'
        - 'bug'
  - title: '🧰 Maintenance'
    when:
      labels:
        - 'chore'
  - title: '🔒 Security'
    when:
      labels:
        - 'security findings'
  - title: '⬆️ Dependency upgrades'
    when:
      labels:
        - 'bump'
        - 'dependencies'
  - type: 'pre-exclude'
    when:
      labels:
        - 'skip-changelog'
template: |
  ## What's Changed
  $CHANGES
