version: "3.1"

services:
  mock-oauth2-server:
    image: mock-oauth2-server:latest
    healthcheck:
      test: ["CMD", "curl", "--retry", "7", "--retry-delay", "1", "--retry-connrefused", "-f", "http://localhost:8080/isalive"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - "8080:8080"
    volumes:
      - ./src/test/resources/config.json:/app/config.json
      - ./src/test/resources/login.example.html:/app/login/login.example.html
      - ./src/test/resources/static/:/app/static/
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8080
      JSON_CONFIG_PATH: /app/config.json
